### ISSUE TITLE
Co-registration by cli

### ISSUE THREAD

**Issue by masud-src** [CBICA/BrainMaGe#17]
Hi,

I just like to ask, if there's a way to use the BraTS_pipeline application via CLI from Linux? Also I would like to know if you know a tool where only one image is processed and not 4 inputs are needed. I was looking around but I am not quite sure what the pipeline is exactly doing.
For testing I put one image for all the modalities...It worked, but its quite inefficient.

Cheers

**Comment by sarthakpati** [comment]
Hi @masud-src,

You can use BraTS_Pipeline from our [Cancer Imaging Phenomics Toolkit (CaPTk)](https://github.com/CBICA/CaPTk). For more information please see: https://cbica.github.io/CaPTk/preprocessing_brats.html

> Also I would like to know if you know a tool where only one image is processed and not 4 inputs are needed

What exactly do you mean? Are you referring to skull stripping or brain extraction? If yes, then BrainMaGe does this. 

> It worked, but its quite inefficient.

Could you please elaborate on what you mean by "inefficient"? Did the process take too long, accuracy was unexpected, or something else entirely?

**Comment by sarthakpati** [comment]
> where a CLI application is mentioned. Later, there is an example command, with an *.exe file. I would like to know, if there is a possibility to use this BraTS_Pipeline CLI with Linux.

Yes, please see https://cbica.github.io/CaPTk/FAQ.html#gs_FAQ_3

> What I want to do, is to use the BrainMaGe Tool for brain extraction, because I just have one modality.

Regarding this, I imagine you would need to do a rigid registration of your data to the [SRI24 atlas](https://github.com/CBICA/CaPTk/blob/master/data/sri24/atlastImage.nii.gz). You could use CaPTk's registration functionality [[ref](https://cbica.github.io/CaPTk/preprocessing_reg.html)] for this:

```bash
${CaPTk_InstallDir}/bin/Preprocessing -i /path/to/single_image.nii.gz -rFI /path/to/sri24.nii.gz -o /path/to/single_image_in_sri_space.nii.gz -reg Rigid
```

**Comment by masud-src** [comment]
Thank you very much! That helped a lot.

**Comment by sarthakpati** [comment]
Glad to have helped.
